# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1248344517);
user_pref("app.update.lastUpdateTime.background-update-timer", 1248344515);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1248344515);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1248344518);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1248344520);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.0.11");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.enabledItems", "langpack-en-GB@firefox-3.0.ubuntu.com:3.0.7,{4ca88e02-7bbb-43fe-ae41-5103893fa10c}:0.33,ubufox@ubuntu.com:0.7,langpack-en-GB@xulrunner-1.9.ubuntu.com:1.9.0.8,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.11");
user_pref("extensions.lastAppVersion", "3.0.11");
user_pref("extensions.update.notifyUser", false);
user_pref("general.warnOnAboutConfig", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("javascript.options.showInConsole", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("nglayout.debug.disable_xul_cache", true);
user_pref("printhint.Preview", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1250936523);
